# Generated by Django 4.1.7 on 2023-10-01 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('installation', models.CharField(max_length=100)),
                ('installation_type', models.CharField(default='', max_length=4)),
                ('installation_date', models.TextField(default='', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=9)),
                ('location_longitude', models.FloatField(default=0)),
                ('location_latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuperuserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
